# Generated by Django 4.1.3 on 2022-12-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_documentorg_documentper_delete_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppliersper',
            old_name='name',
            new_name='firstname',
        ),
    ]
