# Generated by Django 4.1.3 on 2022-12-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_remove_documentorg_suppliersorg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorg',
            name='path',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='documentper',
            name='path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
