# Generated by Django 4.1.3 on 2022-12-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_alter_documentorg_path_alter_documentper_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentorg',
            name='path',
            field=models.ImageField(upload_to='images_sup/'),
        ),
        migrations.AlterField(
            model_name='documentper',
            name='path',
            field=models.ImageField(upload_to='images_sup/'),
        ),
    ]
