# Generated by Django 4.1.3 on 2022-11-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('CustomersOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customersorg')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('CustomersPer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customersper')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
