# Generated by Django 4.1.3 on 2022-11-28 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_documentorg_documentper_delete_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersper',
            old_name='name',
            new_name='firstname',
        ),
    ]
