# Generated by Django 4.1.3 on 2022-12-12 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_name_customersper_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentper',
            name='CustomersPer',
        ),
        migrations.AddField(
            model_name='documentper',
            name='owner',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentper',
            name='path',
            field=models.ImageField(upload_to='images_cus/'),
        ),
    ]
